(function() {var implementors = {};
implementors["tokio_serde_json"] = ["impl&lt;T, U&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a> for <a class='struct' href='tokio_serde_json/struct.ReadJson.html' title='tokio_serde_json::ReadJson'>ReadJson</a>&lt;T, U&gt; <span class='where fmt-newline'>where T: <a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a>&lt;Error=<a class='struct' href='https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html' title='std::io::error::Error'>Error</a>&gt;,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;U: <a class='trait' href='https://docs.serde.rs/serde/de/trait.Deserialize.html' title='serde::de::Deserialize'>Deserialize</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a class='struct' href='https://docs.rs/bytes/0.4/bytes/bytes/struct.Bytes.html' title='bytes::bytes::Bytes'>Bytes</a>: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;T::<a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Item</a>&gt;</span>","impl&lt;T, U&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a> for <a class='struct' href='tokio_serde_json/struct.WriteJson.html' title='tokio_serde_json::WriteJson'>WriteJson</a>&lt;T, U&gt; <span class='where fmt-newline'>where T: <a class='trait' href='https://docs.rs/futures/0.1/futures/stream/trait.Stream.html' title='futures::stream::Stream'>Stream</a> + <a class='trait' href='https://docs.rs/futures/0.1/futures/sink/trait.Sink.html' title='futures::sink::Sink'>Sink</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
